### ISSUE TITLE
Can't delete images

### ISSUE THREAD

**Issue by pwFoo** [genuinetools/reg#47]
Hi @jessfraz 
nice tool! Love it! Thanks for sharing it :)

I have pushed an image to my repo (https, but without auth, registry v2).

**ls**
```
REPO                TAGS
alpine              latest
```

**manifest**
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
     "mediaType": "application/vnd.docker.container.image.v1+json",
     "size": 1512,
     "digest": "sha256:053cde6e8953ebd834df8f6382e68be83adb39bfc063e40b0fc61b4b333938f1"
   },
   "layers": [
     {
       "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
       "size": 1991435,
       "digest": "sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647"
     }
   ]
 }
```

There is no fsLayers blobSum part used to delete / rm the image?
```
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
     "mediaType": "application/vnd.docker.container.image.v1+json",
     "size": 1512,
     "digest": "sha256:053cde6e8953ebd834df8f6382e68be83adb39bfc063e40b0fc61b4b333938f1"
   },
   "layers": [
     {
       "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
       "size": 1991435,
       "digest": "sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647"
     }
   ]
 }
```

Tried layers digest, but image is still there?
```
reg --registry https://... delete alpine:latest@sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
```
Response:
```
Deleted alpine:latest@sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
```

ls
```
REPO                TAGS
alpine              latest```

Any idea?

**Comment by pwFoo** [comment]
I think the registry I used for testing runs with delete disabled... I'll check this.

**Comment by pwFoo** [comment]
Enabled delete by ENV VAR `REGISTRY_STORAGE_DELETE_ENABLED: true`:
```
/ # echo $REGISTRY_STORAGE_DELETE_ENABLED
true
```
and inside the config `/etc/docker/registry/config.yml`:
```
/ # cat /etc/docker/registry/config.yml 
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

But deleted images still there...
```
reg --registry https://myregistry delete alpine@sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
Deleted alpine@sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
```

```
reg --registry https://myregistry delete alpine:latest@sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
Deleted alpine:latest@sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
```

Image is still listed:
```
reg --registry https://myregistry ls
Repositories for https://myregistry
REPO                TAGS
alpine              latest
```
